import Head from "next/head";
import HomePage from "../src/components/home/HomePage";

// Should be used for data that is fetched at request time only.
export const getServerSideProps = async () => {
	const { events_categories } = await import("../data/events.json");

	return {
		props: {
			data: events_categories
		}
	};
};

const Home = ({ data }) => {
	return (
		<>
			<Head>
				<title>Events</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomePage data={data} />
		</>
	);
};

export default Home;
